
#版本检查用，不要修改
version: "v1.0.0 Dev2"

warnMessages:
  onlyPlayer: "&4该指令只能由玩家使用！"
  noPlayer: "&c玩家 %player% 不在线或不存在！"
  invalidNumbers: "&4输入错误！"
  fileError: "&4文件 data.yml 读取失败！"
  reloadSuccess: "&a配置文件重载成功！"

