name: Sky-Fly
version: 'v1.0.0 Beta'
main: top.skyliey.skyfly.Sky_Fly
author: MincHR549, Monostar14
api-version: '1.20'

commands:
  skyfly:
    description: Sky-Fly command.
    usage: /skyfly
    permission: skyfly.skyfly

permissions:
  skyfly.fly:
    description: Allows the player to use the /fly command.
    default: op
  skyfly.flyspeed:
    description: Allows the player to use the /flyspeed command.
    default: op
  skyfly.flypower:
    description: Allows the player to use the /flypower command.
    default: op
  skyfly.skyfly:
    description: Allows the player to use the /skyfly command.
    default: op





