name: Sky-Fly
version: 'v1.0.0 Beta'
main: top.skyliey.skyfly.Sky_Fly
author: MincHR549, Monostar14
api-version: '1.20'

commands:
  skyfly:
    description: Sky-Fly command.
    usage: /skyfly
    permission: skyfly.skyfly

permissions:
  skyfly.use:
    description: 可以飞行的权限。
    default: op
  skyfly.speed:
    description: 可以设置自己飞行速度的权限。
    default: op
  skyfly.energy.set:
    description: 可以设置自己飞行能量的权限。
    default: op
  skyfly.energy.get:
    description: 可以查看自己飞行能量的权限。
    default: op
  skyfly.energy.add:
    description: 可以增加自己飞行能量的权限。
    default: op
  skyfly.energy.remove:
    description: 可以减少自己飞行能量的权限。
    default: op
  skyfly.reload:
    description: 可以重载插件的权限。
    default: op
  skyfly.help:
    description: 可以查看插件帮助的权限。
    default: true




